name: alebda-funnel-site
services:
- name: web
  source_dir: /
  github:
    repo: toufeeqrahimm/AlEbda-Funnel-Site
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  build_command: npm run build
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
